[toolchain]
prefix      = 'aarch64-linux-gnu-'
processor   = 'aarch64'
endianness  = 'little'
cflags      = [
    '-Wall',
    '-Wextra',
    '-D__SUPPORT_RASPI3B__',
    '-D_FORTIFY_SOURCE=0',
    '-ffreestanding',
    '-nostdlib',
    '-fPIE',
    '-O3',
    '-mlittle-endian',
    '-march=armv8-a',
    '-fstrict-volatile-bitfields',
]
ldflags     = [
    '-static',
    '-Wl,-Map=map',
    '-Wl,--build-id=none',
    '-Wl,--emit-relocs',
]
libraries   = [

]
