#ifndef __VHEX_USB_DESCRIPTOR_TYPES_H__
#define __VHEX_USB_DESCRIPTOR_TYPES_H__ 1

#define USB_DESCRIPTOR_DEVICE           1
#define USB_DESCRIPTOR_CONFIGURATION    2
#define USB_DESCRIPTOR_INTERFACE        4
#define USB_DESCRIPTOR_ENDPOINT         5

#endif /* __VHEX_USB_DESCRIPTOR_TYPES_H__ */
